# Generated by Django 4.2.16 on 2024-11-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway_el',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название элемента')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Описание карточки')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Изображение элемента')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание элемента')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gateway.authuser', verbose_name='Создатель элемента')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'db_table': 'gateway_el',
            },
        ),
        migrations.CreateModel(
            name='Gateway_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Введен'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Cтатус')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('form_datetime', models.DateTimeField(null=True)),
                ('complete_datetime', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moder', to=settings.AUTH_USER_MODEL, verbose_name='Модер')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
                'db_table': 'gateway_missions',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='gateway_element_and_mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='el_id', to='gateway.gateway_el')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_id', to='gateway.gateway_mission')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'gateway_element_and_mission',
            },
        ),
        migrations.AddConstraint(
            model_name='gateway_element_and_mission',
            constraint=models.UniqueConstraint(fields=('mission', 'element'), name='mission_el_constraint'),
        ),
    ]
