# Generated by Django 4.2.16 on 2025-02-03 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gateway.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='auth_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='auth_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'custom_auth_user',
            },
            managers=[
                ('objects', gateway.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway_el',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Название элемента')),
                ('short_description', models.TextField(default='', verbose_name='Описание карточки')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('img_url', models.URLField(default='', verbose_name='Изображение элемента')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание элемента')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'db_table': 'gateway_el',
            },
        ),
        migrations.CreateModel(
            name='gateway_element_and_mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addition', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='el_id', to='gateway.gateway_el')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'gateway_element_and_mission',
            },
        ),
        migrations.CreateModel(
            name='Gateway_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введена'), (2, 'В работе'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалена')], default=1, verbose_name='Cтатус')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('form_datetime', models.DateTimeField(null=True)),
                ('complete_datetime', models.DateTimeField(null=True)),
                ('mission_name', models.CharField(blank=True, null=True, verbose_name='Название миссии')),
                ('plan_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата полета')),
                ('addition', models.CharField(blank=True, null=True, verbose_name='Комментарий')),
                ('creator', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('elements', models.ManyToManyField(related_name='missions', through='gateway.gateway_element_and_mission', to='gateway.gateway_el')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moder', to=settings.AUTH_USER_MODEL, verbose_name='Модер')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
                'db_table': 'gateway_missions',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AddField(
            model_name='gateway_element_and_mission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_id', to='gateway.gateway_mission'),
        ),
        migrations.AddConstraint(
            model_name='gateway_element_and_mission',
            constraint=models.UniqueConstraint(fields=('mission', 'element'), name='mission_el_constraint'),
        ),
    ]
