# Generated by Django 4.2.16 on 2025-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway_mission',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
