# Generated by Django 4.2.16 on 2024-11-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_gateway_mission_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_mission',
            name='creator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='gateway.authuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gateway_mission',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moder', to='gateway.authuser', verbose_name='Модер'),
        ),
    ]
