# Generated by Django 4.2.16 on 2024-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_alter_gateway_mission_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway_mission',
            name='elements',
            field=models.ManyToManyField(related_name='missions', through='gateway.gateway_element_and_mission', to='gateway.gateway_el'),
        ),
        migrations.AddField(
            model_name='gateway_mission',
            name='mission_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название миссии'),
        ),
        migrations.AddField(
            model_name='gateway_mission',
            name='plan_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата полета'),
        ),
    ]
