# Generated by Django 4.2.16 on 2024-11-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_gateway_mission_elements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway_mission',
            old_name='plan_data',
            new_name='plan_date',
        ),
    ]
