# Generated by Django 4.2.16 on 2024-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_rename_plan_data_gateway_mission_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway_element_and_mission',
            name='element_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
