# Generated by Django 4.2.16 on 2024-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_gateway_element_and_mission_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_element_and_mission',
            name='element_type',
            field=models.CharField(blank=True, choices=[(1, 'Модуль станции'), (2, 'Космический корабль')], null=True),
        ),
    ]
