# Generated by Django 4.2.16 on 2024-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_gateway_element_and_mission_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_element_and_mission',
            name='element_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Модуль станции'), (2, 'Космический корабль')], null=True),
        ),
        migrations.AlterField(
            model_name='gateway_mission',
            name='status',
            field=models.IntegerField(choices=[(1, 'Введен'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Cтатус'),
        ),
    ]
