# Generated by Django 4.2.16 on 2024-12-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_alter_gateway_element_and_mission_element_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway_el',
            old_name='user',
            new_name='creator',
        ),
    ]
