# Generated by Django 4.2.16 on 2024-12-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_rename_user_gateway_el_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway_mission',
            name='status',
            field=models.IntegerField(choices=[(1, 'Введена'), (2, 'В работе'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалена')], default=1, verbose_name='Cтатус'),
        ),
    ]
