# Generated by Django 4.2.16 on 2024-12-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_alter_gateway_mission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway_el',
            name='creator',
        ),
    ]
